/*
 * buildopts.h 
 * Automatically generated
 */

#define LOADABLE_MODULES 1
#define BUILD_NATIVE 1
#define AST_MODULE_CHAN_LOCAL 1
#define AST_MODULE_APP_VOICEMAIL 1
#define AST_MODULE_APP_CONFBRIDGE 1
#define AST_MODULE_RES_MONITOR 1
#define AST_MODULE_RES_AGI 1
#define AST_MODULE_RES_ADSI 1
#define AST_MODULE_RES_SMDI 1
#define AST_MODULE_RES_CRYPTO 1
#define AST_MODULE_RES_HTTP_WEBSOCKET 1
#define AST_MODULE_RES_AEL_SHARE 1
#define AST_MODULE_RES_FAX 1
#define AST_MODULE_G711_NEW_ALGORITHM 1
#define AST_BUILDOPT_SUM "b08aeedfd399b0dd3c1e2f00c3b0673c"
#define AST_BUILDOPTS "LOADABLE_MODULES, BUILD_NATIVE"
